# Generated by Django 4.1.8 on 2023-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NE', 'New'), ('IP', 'In Process'), ('ST', 'Stored'), ('SE', 'Send')], default='NE', max_length=2)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
